name: Latex compile Thesis

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: thesis

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'
          cache: pip

      - name: Install Pygments
        run: pip install pygments

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Download Times New Roman
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
          sudo fc-cache -rv

      - name: Install latex
        run: sudo apt-get install texlive
      
      - name: Compile Latex
        working-directory: thesis
        run: latexmk --shell-escape -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode main.tex -o thesis.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Thesis
          path: thesis/thesis.pdf
          if-no-files-found: error
          