name: Latex compile Thesis

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: thesis

      - name: Install required packages
        run: sudo apt install texlive latexmk texlive-xetex texlive-lang-european xz-utils python3-pygments

      - name: Install Times New Roman
        run: |
          curl -L -O https://notabug.org/ArtikusHG/times-new-roman/raw/master/times.tar.xz
          sudo tar -xf times.tar.xz -C /usr/share/fonts/
          fc-cache -f -v
      
      - name: Compile PDF with Latex
        working-directory: thesis
        run: |
          latexmk --shell-escape -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode main.tex
          mv main.pdf thesis.pdf

      - name: Upload the PDF
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Thesis
          path: thesis/thesis.pdf
          if-no-files-found: error
          
