name: Latex compile Thesis

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pip
        uses: BSFishy/pip-action@v1
        with:
          packages: pygments

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Download Time New Roman
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
          sudo fc-cache -rv
      
      - name: Compile Latex
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: main.tex
          working_directory: thesis
          args: --shell-escape -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode

      - name: Rename output PDF
        run: mv thesis/main.pdf thesis/thesis.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Thesis
          path: thesis/thesis.pdf
          if-no-files-found: error
          

